config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get "/home/about" => "homes#about", as: "about"
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy,]
  resources :users, only: [:show, :index, :edit, :update,]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true
  validates :name, length: {minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "You have updated book successfully."
     redirect_to book_path(@book.id)
    else
     render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @new_book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
 <h2>User Info</h2>

 <div><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg"%></div>
 <table class="table">
  <thead>
   <tr>
     <th>name</th>
     <th><%= user.name %></th>
   </tr>
  </thead>

  <thead>
   <tr>
     <th>introduction</th>
     <th><%= user.introduction %></th>
   </tr>
  </thead>
 </table>
 <div class="row">
  <%= link_to (edit_user_path(user)) , class: 'btn btn-outline-secondary btn-block' do %><span class="fas fa-user-cog text-secondary"></span><% end %>
 </div>

 <h2 class="mt-3">New book</h2>
 <%= form_with model: book, local:true do |f| %>
   <div class="form-group">
    <div class="field">
      <label for="book_title">Title</label><br />
      <%= f.text_field :title , class: 'form-control' %>
    </div>
   </div>
   <div class="form-group">
    <div class="area">
      <label for="book_body">Opinion</label><br />
      <%= f.text_area :body , class: 'form-control' %>
    </div>
   </div>
   <div class="form-group">
    <%= f.submit 'Create Book' , class: 'btn btn-success' %>
   </div>
 <% end %>
 </div>

app/views/books/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h1>Editing Book</h1>
   <% if @book.errors.any? %>
    <div class="errors">
     <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
     <ul>
      <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
    </div>
   <% end %>

   <%= form_with model: @book, local:true do |f| %>
    <div class="form-group">
     <div class="field">
       <label for="book_title">Title</label><br />
       <%= f.text_field :title , class: 'form-control' %>
     </div>
    </div>
    <div class="form-group">
     <div class="area">
      <label for="book_body">Opinion</label><br />
      <%= f.text_area :body , class: 'form-control' %>
     </div>
    </div>
    <div class="form-group">
     <%= f.submit 'Update Book' , class: 'btn btn-success' %>
    </div>
   <% end %>
   <span><%= link_to "Show", book_path(@book) %></span>|<span><%= link_to 'Back', books_path %></span>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
   <div class="errors">
    <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
    <ul>
     <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
    </ul>
   </div>
  <% end %>
 <div class="row">
  <%= render 'books/list', book: @book, user: current_user %>
  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
   <table class="table table-hover table-inverse">
     <thead>
       <tr>
         <th></th>
         <th>Title</th>
         <th>Opinion</th>
         <th colspan="3"></th>
       </tr>
     </thead>

     <tboy>
         <% @books.each do |book| %>
           <tr>
             <td><%= link_to user_path(book.user.id) do %><%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg"%><% end %></td>
             <td><%= link_to book.title, book_path(book.id) %></td>
             <td><%= book.body %></td>
           </tr>
         <% end %>
     </tboy>
   </table>
  </div>
 </div>
</div>

app/views/books/show.html.erb
<div class="container">
 <div class="row">
  <%= render 'books/list', book: @new_book, user: @book.user %>
  <div class="col-md-8 offset-md-1">
   <h2>Book detail</h2>
   <table class="table">
    <tboy>
     <tr>
      <td><%= attachment_image_tag @book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg"%><br /><%= link_to @book.user.name, user_path(@book.user) %></td>
      <td><%= @book.title %></td>
      <td><%= @book.body %></td>
      <% if @book.user.id == current_user.id %>
       <td><%= link_to 'Edit', edit_book_path(@book) , class: 'btn btn-success' %></td>
       <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: {confirm: '本当に消しますか' } , class: 'btn btn-danger' %></td>
      <% end %>
     </tr>
    </tboy>
   </table>
  </div>
 </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="p-3 mx-auto">
      Welcome to<i class="fas fa-book"></i>
      <strong>Bookers!!</strong>
     </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
     <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          Welcome to<i class="fas fa-book"></i>
          <strong>Bookers!!</strong>
        </h1>
        <p>
          In<i class="fas fa-book"></i>
          <strong>Bookers</strong>
          ,
        </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
           <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
           <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
     </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header class="shadow-sm">
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
           <li class="nav-item p-2"><%= link_to (user_path(current_user.id)) do %><span class="fas fa-home text-light">Home</span><% end %></li>
           <li class="nav-item p-2"><%= link_to (users_path) do %><span class="fas fa-users text-light">Users</span><% end %></li>
           <li class="nav-item p-2"><%= link_to (books_path) do %><span class="fas fa-book-open text-light">Books</span><% end %></li>
           <li class="nav-item p-2"><%= link_to (destroy_user_session_path), method: :delete do %><span class="fas fa-sign-out-alt text-light">Log out</span><% end %></li>
         <% else %>
          <li class="nav-item p-2"><%= link_to (root_path) do %><span class="fas fa-home text-light">Home</span><% end %></li>
          <li class="nav-item p-2"><%= link_to (about_path) do %><span class="fas fa-link text-light">About</span><% end %></li>
          <li class="nav-item p-2"><%= link_to (new_user_registration_path) do %><span class="fas fa-user-plus text-light">Sign up</span><% end %></li>
          <li class="nav-item p-2"><%= link_to (new_user_session_path) do %><span class="fas fa-sign-in-alt text-light">Log in</span><% end %></li>
         <% end %>
         </ul>
        </div>
       </div>
      </nav>
    </header>
    <main>
      <% flash.each do |key, value| %>
       <%=content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h2>User info</h2>
   <% if @user.errors.any? %>
    <div class="errors">
     <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
     <ul>
      <% @user.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
     </ul>
    </div>
   <% end %>
   <%= form_with model: @user, local:true do |f| %>
     <div class="form-group">
       <label for="inputName">Name</label>
       <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name" , class: 'form-control' %>
     </div>
     <div class="form-group">
       <label for="inputImage">Image</label>
       <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
     </div>
     <div class="form-group">
       <label for="inputIntoroduction">Intoroduction</label>
       <%= f.text_area :introduction, autofocus: true, id:"inputIntoroduction", placeholder:"Introduction" , class: 'form-control' %>
     </div>
     <div class="form-group">
      <%= f.submit "Update User" , class: 'btn btn-secondary' %>
     </div>
   <% end %>
  </div>
 </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <%= render 'books/list', book: @new_book, user: current_user %>
  <div class="col-md-8 offset-md-1">
   <h2>Users</h2>
   <table class="table">
     <thead>
       <tr>
         <th>image</th>
         <th>name</th>
         <th colspan="3"></th>
       </tr>
     </thead>

     <tboy>
         <% @users.each do |user| %>
           <tr>
             <td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg"%></td>
             <td><%= user.name %></td>
             <td><%= link_to 'Show', user_path(user.id) %></td>
           </tr>
         <% end %>
     </tboy>
   </table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <%= render 'books/list', book: @new_book, user: @user %>
  <div class="col-md-8 offset-md-1">
  <h2>Books</h2>
   <table class="table table-hover table-inverse">
       <thead>
         <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th colspan="3"></th>
         </tr>
       </thead>

       <tboy>
           <% @books.each do |book| %>
             <tr>
               <td><%= link_to user_path(@user.id) do %><%= attachment_image_tag @user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg"%><% end %></td>
               <td><%= link_to book.title, book_path(book.id) %></td>
               <td><%= book.body %></td>
             </tr>
           <% end %>
       </tboy>
   </table>
  </div>
 </div>
</div>